CREATE DATABASE REGIONALIZACAO DEFAULT CHARACTER SET Latin1 COLLATE = latin1_swedish_ci;


USE REGIONALIZACAO;



CREATE TABLE PAIS (
  IDPAIS INT  NOT NULL   ,
  NOMEPAIS VARCHAR(64)    ,
  DDI SMALLINT    ,
  LINGUA VARCHAR(5)      ,
PRIMARY KEY(IDPAIS));



CREATE TABLE REGIAO (
  IDREGIAO INT  NOT NULL  ,
  IDPAIS INT  NOT NULL  ,
  NOMEREGIAO VARCHAR(64)      ,
PRIMARY KEY(IDREGIAO),
  FOREIGN KEY(IDPAIS)
    REFERENCES PAIS(IDPAIS));



CREATE TABLE ESTADO (
  IDESTADO INT  NOT NULL   ,
  IDREGIAO INT  NOT NULL  ,
  NOMEESTADO VARCHAR(64)    ,
  UF CHAR(2)      ,
PRIMARY KEY(IDESTADO),
  FOREIGN KEY(IDREGIAO)
    REFERENCES REGIAO(IDREGIAO));



CREATE TABLE MESOREGIAO (
  IDMESOREGIAO INT  NOT NULL   ,
  IDESTADO INT  NOT NULL  ,
  NOMEMESOREGIAO VARCHAR(64)      ,
PRIMARY KEY(IDMESOREGIAO),
  FOREIGN KEY(IDESTADO)
    REFERENCES ESTADO(IDESTADO));



CREATE TABLE MICROREGIAO (
  IDMICROREGIAO INT  NOT NULL   ,
  IDMESOREGIAO INT  NOT NULL  ,
  NOMEMICROREGIAO VARCHAR(64)      ,
PRIMARY KEY(IDMICROREGIAO),
  FOREIGN KEY(IDMESOREGIAO)
    REFERENCES MESOREGIAO(IDMESOREGIAO));



CREATE TABLE MUNICIPIO (
  IDMUNICIPIO INT  NOT NULL  ,
  IDMICROREGIAO INT  NOT NULL  ,
  NOMEMUNICIPIO VARCHAR(64)      ,
PRIMARY KEY(IDMUNICIPIO),
  FOREIGN KEY(IDMICROREGIAO)
    REFERENCES MICROREGIAO(IDMICROREGIAO));



